### ISSUE TITLE
"SyntaxError: Unexpected non-whitespace character..." from JSON response

### ISSUE THREAD

**Issue by andyhorn** [supabase/cli#1597] opened 2023-10-22 06:08 UTC
**Describe the bug**

I'm running Supabase locally while developing a Flutter app and am seeing a reproducible error when submitting a OTP during an email-change flow. Upon submitting the token, a SyntaxError is being thrown from the `GotrueFetch` class. 

```
SyntaxError: Unexpected non-whitespace character after JSON at position 105 (line 1 column 106)
```

It comes from a `json.decode(utf8.decode(response.bodyBytes))` call and, after debugging, it appears that I'm actually getting invalid JSON back from the `POST` request.

```
{"code":"200","msg":"Confirmation link accepted. Please proceed to confirm link sent to the other email"}null
```

The request is successful but the body is invalid and failing to parse.

**To Reproduce**
I haven't seen this for any request other than verifying an OTP for an email change.

1. Submit a request to update the user's email (`updateUser` in the Flutter SDK)
2. Retrieve the OTP from `inbucket`
3. Submit a request to verify the OTP (`verifyOTP` in the Flutter SDK)

**Expected behavior**

I expected to submit my OTP without error.

**Screenshots**

<img width="1145" alt="Screenshot 2023-10-21 at 10 59 08 PM" src="https://github.com/supabase/cli/assets/13260228/ba8e4922-9b76-4bd8-84f5-a861eb81575d">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Chrome (118.0.5993.88)
 - Version of CLI: 1.100.1

**Edit**:

I'm using `supabase_flutter` version `^1.10.22`

**Comment by sweatybridge** [comment] 2023-10-25 04:23
I've pinged our teams internally and it doesn't seem like an issue with gotrue. Tagging @dshukertjr here as he's more familiar with our flutter sdk and might be able to help.

**Comment by dshukertjr** [comment] 2023-10-25 10:51
@andyhorn 
I am using the Supabase CLI v1.106.1, and I am unable to reproduce the issue you are experiencing. Would you be able to update your Supabase CLI and see if you will still encounter the same issue?

However, I did find a separate issue that will throw an error when verifying the OTP sent to the email just after the json parsing part. The following PR should fix the SDK issue. https://github.com/supabase/supabase-flutter/pull/680

**Comment by sweatybridge** [comment] 2023-10-30 09:11
@andyhorn if you are still facing this issue, could you report your local service versions to help us reproduce?

```bash
supabase services
```

I will close this for now as it seems fixed in the latest release.

**Closed by sweatybridge** 2023-10-30 09:11 UTC

**Comment by andyhorn** [comment] 2023-11-02 20:04
I apologize for not responding in time.

I wrote some workaround code, but I can still reproduce this, even after updating to 1.110.1.

Another note: It only happens if I try to validate the OTP from the new email address _before_ verifying the OTP from the previous/current email address.

**Comment by andyhorn** [comment] 2023-11-02 20:09
```
server % supabase -v
1.110.1

server % supabase services

  
        SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.117           │ 15.1.0.113
    supabase/gotrue        │ v2.92.1              │ v2.104.2
    postgrest/postgrest    │ v11.2.0              │ v11.2.0
    supabase/realtime      │ v2.10.1              │ -
    supabase/storage-api   │ v0.40.4              │ v0.43.9
    supabase/edge-runtime  │ v1.22.3              │ -
    supabase/studio        │ 20231023-7e2cd92     │ -
    supabase/postgres-meta │ v0.68.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

Run supabase link to sync your local image versions with the linked project.
```
