### ISSUE TITLE
Can't run supabase db start

### ISSUE THREAD

**Issue by jpotosme-sjrtd** [supabase/cli#1383] opened 2023-08-17 16:16 UTC
**Describe the bug**
I am facing a database is not healthy error when running supabase cli for the first time.

**To Reproduce**
1. Download the cli
2. run npx supabase init
3. run npx supabase db start
4. See "database is not healthy"

**Expected behavior**
The database should start as I am just choosing to run that portion atm.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version of CLI : 1.86.1
 - Version of Node.js : v18.12.1
 - Version of Docker: Docker version 24.0.5, build ced0996

**Additional context**
Here are the logs having run with debug flag.
```
npx supabase db start --debug
Supabase CLI 1.86.1
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:37 Recv First Byte
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:37 Recv First Byte
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:37 Recv First Byte
Starting database...
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:37 Recv First Byte
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Sent Header: Content-Length [306]
2023/08/17 08:57:37 Sent Header: Content-Type [application/json]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:37 Recv First Byte
2023/08/17 08:57:37 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:37 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:37 Sent Header: Content-Length [11457]
2023/08/17 08:57:37 Sent Header: Content-Type [application/json]
2023/08/17 08:57:37 Send Done
2023/08/17 08:57:39 Recv First Byte
2023/08/17 08:57:39 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:39 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:39 Sent Header: Content-Length [0]
2023/08/17 08:57:39 Sent Header: Content-Type [text/plain]
2023/08/17 08:57:39 Send Done
2023/08/17 08:57:41 Recv First Byte
2023/08/17 08:57:41 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:41 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:41 Send Done
2023/08/17 08:57:41 Recv First Byte
2023/08/17 08:57:42 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:42 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:42 Send Done
2023/08/17 08:57:42 Recv First Byte
2023/08/17 08:57:43 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:43 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:43 Send Done
2023/08/17 08:57:43 Recv First Byte
2023/08/17 08:57:44 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:44 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:44 Send Done
2023/08/17 08:57:44 Recv First Byte
2023/08/17 08:57:45 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:45 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:45 Send Done
2023/08/17 08:57:45 Recv First Byte
2023/08/17 08:57:46 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:46 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:46 Send Done
2023/08/17 08:57:46 Recv First Byte
2023/08/17 08:57:47 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:47 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:47 Send Done
2023/08/17 08:57:47 Recv First Byte
2023/08/17 08:57:48 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:48 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:48 Send Done
2023/08/17 08:57:48 Recv First Byte
2023/08/17 08:57:49 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:49 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:49 Send Done
2023/08/17 08:57:49 Recv First Byte
2023/08/17 08:57:50 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:50 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:50 Send Done
2023/08/17 08:57:50 Recv First Byte
2023/08/17 08:57:51 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:51 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:51 Send Done
2023/08/17 08:57:52 Recv First Byte
2023/08/17 08:57:52 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:52 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:52 Send Done
2023/08/17 08:57:52 Recv First Byte
2023/08/17 08:57:53 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:53 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:53 Send Done
2023/08/17 08:57:53 Recv First Byte
2023/08/17 08:57:54 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:54 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:54 Send Done
2023/08/17 08:57:54 Recv First Byte
2023/08/17 08:57:55 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:55 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:55 Send Done
2023/08/17 08:57:55 Recv First Byte
2023/08/17 08:57:56 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:56 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:56 Send Done
2023/08/17 08:57:56 Recv First Byte
2023/08/17 08:57:57 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:57 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:57 Send Done
2023/08/17 08:57:57 Recv First Byte
2023/08/17 08:57:58 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:58 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:58 Send Done
2023/08/17 08:57:58 Recv First Byte
2023/08/17 08:57:59 Sent Header: Host [api.moby.localhost]
2023/08/17 08:57:59 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:57:59 Send Done
2023/08/17 08:57:59 Recv First Byte
2023/08/17 08:58:00 Sent Header: Host [api.moby.localhost]
2023/08/17 08:58:00 Sent Header: User-Agent [Docker-Client/unknown-version (windows)]
2023/08/17 08:58:00 Send Done
2023/08/17 08:58:00 Recv First Byte
database is not `healthy`
```

When running docker ps, it will run  for about 20 seconds then timeout.
```
docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS                            PORTS                     NAMES
aa0cc032a1f3   public.ecr.aws/supabase/postgres:15.1.0.103   "sh -c 'cat <<'EOF' …"   9 seconds ago   Up 4 seconds (health: starting)   0.0.0.0:54322->5432/tcp   supabase_db_cli_demo
```
When running docker stats on the container, I see that there is 12 gb mem limit but the container still fails to give healthy signal.
```
docker stats 3d35c98b9f35
CONTAINER ID   NAME                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O       BLOCK I/O   PIDS
3d35c98b9f35   supabase_db_cli_demo   0.08%     105.6MiB / 12.42GiB   0.83%     1.11kB / 0B   0B / 0B     14 
```

I have also checked if anything is running on the ports in the config.toml with netstat -aon | find /i "listening"  and they are free.

Any help on what may be causing this issue would be much appreciated, looking to separate my dev / prod environments.

**Comment by sweatybridge** [comment] 2023-08-18 01:50
Closing as duplicate of https://github.com/supabase/cli/issues/1384. We have fixed it 1.86.2

**Closed by sweatybridge** 2023-08-18 01:50 UTC

**Comment by jpotosme-sjrtd** [comment] 2023-08-18 15:39
I am still encountering the same issue after having deleted the images and updated the cli to 1.86.2. 
"database is not healthy" and I can't seem to run the --ignore-health-check flag with npx supabase db start .

**Comment by AyushSehrawat** [comment] 2023-08-20 15:04
I am still facing it on Pop 22.04 with cli version 1.86.2.
Mentioned in the discord server too: https://discord.com/channels/839993398554656828/1142832328842940446/1142832328842940446

And i see no .temp folder as mentioned in #1384

**Comment by aboubakrbm** [comment] 2023-08-20 21:18
same issue with version 1.82.2
``` bash
npx supabase db reset
Resetting local database...
Restarting containers...
database is not healthy
```
