### ISSUE TITLE
supabase-auth can't connect to db, seems to ignore port setting

### ISSUE THREAD

**Issue by tgle** [supabase/cli#49] opened 2021-09-04 06:12 UTC
Thanks for your work! I've had some trouble getting supabase set up locally for development. When specifying different port options in `supabase init`, the `supabase-auth` docker container exits on start with the following message:

```
04T06:02:46Z" level=fatal msg="failed to connect to `host=db user=postgres database=postgres`: dial error (dial tcp 172.18.0.3:5432: connect: connection refused)\ncould not create new transaction\ngithub.com/gobuffalo/pop/v5.newTX\n\t/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.3.4/tx.go:29\ngithub.com/gobuffalo/pop/v5.
```

I specified 5434 for the db rather than 5432 (as I already have a different postgres running on localhost), so it looks like it's ignoring that and trying to use the default. If I stop my other postgres and use the default ports instead, it all works fine.

**Comment by soedirgo** [comment] 2021-09-06 08:20
Hey, sorry about this - from the error message, it looks like it's trying to connect to port 5432 on the `db` container, which looks right to me (the port setting during setup is for host).

I think the problem is the images used in the Compose file aren't pinned, so it tries to use the latest `supabase/gotrue` image which may have breaking changes.

I'm working on a [rewrite](https://github.com/supabase/cli/tree/new) of the CLI, so any fix for this probably won't land, but I'll make sure to keep issues like this in mind.

**Comment by soedirgo** [comment] 2021-11-10 14:52
With the new CLI `auth` should be able to find the db regardless of the port settings, but feel free to reopen if the issue resurfaces.

**Closed by soedirgo** 2021-11-10 14:52 UTC
Labels: bug
