### ISSUE TITLE
Error: service not healthy

### ISSUE THREAD

**Issue by mokshsinghji** [supabase/cli#816] opened 2023-01-27 20:51 UTC
# Bug report

## Describe the bug

When I run `$ supabase start`, I get the error:
```Error restoring main: branch was not dumped.
Seeding data supabase\seed.sql...
Error: service not healthy: [realtime-dev.supabase_realtime_todo-list supabase_storage_todo-list supabase_pg_meta_todo-list supabase_studio_todo-list]
Try rerunning the command with --debug to troubleshoot the error.
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Install the supabase cli with
```
$ scoop bucket add supabase https://github.com/supabase/scoop-bucket.git
$ scoop install supabase
```

Run 
```
$ supabase init
```
Then:
```
$ supabase init
```

## Expected behavior

Should start the docker containers

## System information

- OS: Windows 11
- Version of Node.js: v18.10.0

**Comment by sweatybridge** [comment] 2023-01-29 03:53
Could you try this flag `supabase start --ignore-health-check`?

Currently the local development stack starts very slowly when there's less than 7GB of RAM available. So you can ignore health check as a workaround until we reduce the memory usage of the docker containers started.

**Comment by sweatybridge** [comment] 2023-01-31 03:59
closing as duplicate of https://github.com/supabase/cli/issues/778

**Closed by sweatybridge** 2023-01-31 03:59 UTC
Labels: bug
