### ISSUE TITLE
New Column button doesn't work

### ISSUE THREAD

**Issue by sergchernata** [supabase/cli#1529] opened 2023-09-26 17:25 UTC
**Describe the bug**
Opening the "New Column" pane in studio UI doesn't work. No obvious error messages are shown either.

**To Reproduce**
1. Go to `http://localhost:54323/project/default/database/tables`
2. Click on `profile` table
3. Click on "New Column" button on top right
4. See that nothing happens

**Expected behavior**
Should slide out a pane on the right side for addition of a new column

**Desktop (please complete the following information):**
 - Version of CLI [1.99.10]

**Additional context**
Not entirely sure if it's related but this is the only error I see in console:

```
http://localhost:54323/api/integrations/default-org-slug?expand=true 404 (Not Found)
```

**Comment by sweatybridge** [comment] 2023-11-09 04:24
This is probably fixed in latest studio release as I'm not able to reproduce.

![Screenshot 2023-11-09 at 12 24 15 PM](https://github.com/supabase/cli/assets/1639722/20e29370-bc8b-4032-9007-4592664c8e8d)

**Closed by sweatybridge** 2023-11-09 04:24 UTC
