### ISSUE TITLE
seeding script fails on auth.users

### ISSUE THREAD

**Issue by CareTiger** [supabase/cli#1258] opened 2023-06-27 18:19 UTC
**Describe the bug**
Error: ERROR: column "email_confirmed_at" of relation "users" does not exist (SQLSTATE 42703)

```
Seeding data supabase\seed.sql...
2023/06/27 13:15:48 PG Send: {"Type":"Parse","Name":"lrupsc_2_0","Query":"INSERT INTO \"auth\".\"users\" (\"instance_id\", \"id\", \"aud\", \"role\", \"email\", \"encrypted_password\", \"email_confirmed_at\", \"invited_at\", \"confirmation_token\", \"confirmation_sent_at\", \"recovery_token\", \"recovery_sent_at\", \"email_change_token_new\", \"email_change\", \"email_change_sent_at\", \"last_sign_in_at\", \"raw_app_meta_data\", \"raw_user_meta_data\", \"is_super_admin\", \"created_at\", \"updated_at\", \"phone\", \"phone_confirmed_at\", \"phone_change\", \"phone_change_token\", \"phone_change_sent_at\", \"email_change_token_current\", \"email_change_confirm_status\", \"banned_until\", \"reauthentication_token\", \"reauthentication_sent_at\", \"is_sso_user\") VALUES\r\n('00000000-0000-0000-0000-000000000000', '521e7bfc-f75a-4f96-80f3-aac9979597e2', 'authenticated', 'authenticated', 'joker@example.com', crypt('minnie', gen_salt('bf')), '2023-02-18 23:31:13.017218+00', NULL, '', '2023-02-18 23:31:12.757017+00', '', NULL, '', '', NULL, '2023-02-18 23:31:13.01781+00', '{\"provider\": \"email\", \"providers\": [\"email\"]}', '{}', NULL, '2023-02-18 23:31:12.752281+00', '2023-02-18 23:31:13.019418+00', NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, 'f')","ParameterOIDs":null}        
2023/06/27 13:15:48 PG Send: {"Type":"Describe","ObjectType":"S","Name":"lrupsc_2_0"}
2023/06/27 13:15:48 PG Send: {"Type":"Sync"}
2023/06/27 13:15:48 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42703","Message":"column \"email_confirmed_at\" of relation \"users\" does not exist","Detail":"","Hint":"","Position":96,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"parse_target.c","Line":1061,"Routine":"checkInsertTargets","UnknownFields":null}
2023/06/27 13:15:48 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
Restarting containers...
2023/06/27 13:15:48 PG Send: {"Type":"Terminate"}
```

$ supabase --version
1.74.0

$ docker --version
Docker version 24.0.2, build cb74dfc

windows 11

**To Reproduce**

- update supabase cli. 
- run `supabase db reset`

**Expected behavior**
seeding should be successful!

**Screenshots**

**Comment by sweatybridge** [comment] 2023-06-27 19:49
Closing as a duplicate of https://github.com/supabase/cli/issues/1255

**Closed** 2023-06-27 19:48 UTC
