### ISSUE TITLE
`supabase db diff` and `supabase db pull` not capturing RLS policies in views

### ISSUE THREAD

**Issue by officialankan** [supabase/cli#2264] opened 2024-05-10 05:00 UTC
**Describe the bug**
I love views with RLS to reduce complex queries. I also like local development. When combining the two I always have to manually add the RLS part when pushing or pulling migrations.

**To Reproduce**
1. Create a view with RLS (`security_invoker=true`) remotely or localy.
2. pull or push
3. in the generated diff, the `security_invoker` is not always there (I have seen it sometime, but can't see why it won't show anymore)

**Expected behavior**
The full settings of the view should be diffed.

**System information**
![bild](https://github.com/supabase/cli/assets/13569761/77875196-8707-4f63-bf51-cb0060db06c1)

Much love! I really enjoy supabase.

**Comment by sweatybridge** [comment] 2024-05-14 14:36
Is this a duplicate of #792?

**Comment by officialankan** [comment] 2024-05-14 16:04
> Is this a duplicate of #792?

Yes, it is...

**Comment by sweatybridge** [comment] 2024-05-29 04:57
Thanks for confirming. I will close this issue as a duplicate.

The fix requires updating the underlying diff tool from migra to pg-schema-diff. It will likely be addressed by this upstream PR when it's merged https://github.com/stripe/pg-schema-diff/pull/132

**Closed by sweatybridge** 2024-05-29 04:57 UTC

**Comment by bplunkett-stripe** [comment] 2024-05-29 20:20
> >Thanks for confirming. I will close this issue as a duplicate.
> 
> The fix requires updating the underlying diff tool from migra to pg-schema-diff. It will likely be addressed by this upstream PR when it's merged https://github.com/stripe/pg-schema-diff/pull/132
> 

pg-schema-diff doesn't support views yet. So that [will need to be implemented fist](https://github.com/stripe/pg-schema-diff/issues/135).
