### ISSUE TITLE
Supabase start throws error

### ISSUE THREAD

**Issue by ananth243** [supabase/cli#665] opened 2022-12-04 16:26 UTC
# Bug report

## Describe the bug

Using supabase in my next js project and have a remote instance setup also. ```supabase start``` throws error:
```Database is not healthy```

## To Reproduce
```
supabase login
supabase init
supabase start
```

## Expected behavior

![image](https://user-images.githubusercontent.com/75936896/205502296-8db4ceef-f89c-40cb-bc57-2ae00a5e2982.png)

## Screenshots
![image](https://user-images.githubusercontent.com/75936896/205502373-93e3d4a1-8d77-4d53-947b-6bb73a356674.png)

With ```--debug```

![image](https://user-images.githubusercontent.com/75936896/205502395-f4dd7ffd-157b-4832-9a24-88e5cca8204f.png)

## System information

- OS: Ubuntu 21.04
- Version of supabase-js: ^2.1.1
- Version of Node.js: 19.0.0

**Comment by sweatybridge** [comment] 2022-12-04 17:00
Hello, could you paste here the docker logs after supabase start?

```
$ docker logs supabase_db_my_project
```

**Comment by sweatybridge** [comment] 2022-12-04 18:29
The logs look normal. Does `supabase db start` work? This command only starts the db container.

**Comment by ananth243** [comment] 2022-12-04 19:06
@sweatybridge when I ran it the first time, it worked.
But when I ran ```supabase stop``` and ran the command again I got the following error:
```bash
Starting database...
Database is not healthy.
Error: failed to connect to `host=localhost user=postgres database=postgres`: failed to receive message (read tcp 127.0.0.1:36606->127.0.0.1:54322: read: connection reset by peer)
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by sweatybridge** [comment] 2022-12-05 15:58
As a sanity check, could you run the following commands before supabase start?

```
docker ps -a
docker network ls
```

Then after supabase start, run those commands again. Compare the state before and after could help diagnose this problem.

**Comment by sweatybridge** [comment] 2022-12-08 07:20
Another thing to check is the disk space allocated to docker. To be KN the safe side, you want to leave about 20GB of free space for docker before running supabase start.

**Comment by sweatybridge** [comment] 2022-12-08 07:22
Closing this as can't reproduce. Let me know if you have more information.

**Closed** 2022-12-08 07:21 UTC
Labels: bug
