### ISSUE TITLE
Generated types for a view do not match the original table

### ISSUE THREAD

**Issue by chrism** [supabase/cli#1004] opened 2023-04-08 08:02 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

I was advised by silentworks to raise this as a bug here after posting on the Supabase discord
https://discord.com/channels/839993398554656828/1086948087316086864

## Describe the bug

The typescript types generated for a view don't seem to match the types for the columns on the table they are based on. They add the possibility for null as an alternative, even if the original column is explicitly set to not null.

## To Reproduce

A table called `playlists` has a column called `first_play` which is a non nullable boolean.

```
alter table "public"."playlists" add column "first_play" boolean not null default false;
```

The generated typescript for this column is as expected

```
first_play: boolean
```

But with a view generated like this

```
CREATE OR REPLACE VIEW public.tracklists AS
  SELECT
    playlists.first_play AS first_play
  FROM playlists
``` 

The generated types file produces this

```
first_play: boolean | null
```

## Expected behavior

I would expect that the generated typescript definition would match the column the view is based on and not add null as a possible option.

## System information

- OS: macOS
- Version of supabase CLI: 1.42.7

**Comment by bentilling** [comment] 2023-09-26 07:30
For anyone else that also stumbles on this issue, I looked into fixing it but unfortunately looks like a nuance with Postgres, all view columns are set as nullable, [some discussion](https://stackoverflow.com/questions/17301323/why-are-my-views-columns-nullable) so doesn't seem anything can be done on Supabase side.

**Comment by soedirgo** [comment] 2024-03-14 05:03
Closing as duplicate of https://github.com/supabase/cli/issues/577

**Closed by soedirgo** 2024-03-14 05:03 UTC
Labels: bug, typegen
