### ISSUE TITLE
`supabase start` Error: service not healthy

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#1083] opened 2023-05-09 22:03 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`supabase start` fails after updating to the latest version.

## To Reproduce

`supabase start`

## Logs

`supabase start --debug` logs:
```
[...]
supabase_pg_meta_limey container logs:

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/app.js

(node:36) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2023/05/09 23:57:31 Sent Header: Host [docker]
2023/05/09 23:57:31 Sent Header: User-Agent [Go-http-client/1.1]
2023/05/09 23:57:31 Send Done
2023/05/09 23:57:31 Recv First Byte
supabase_studio_limey container logs:
info  - Loaded env from /app/studio/.env
Listening on port 3000
Error: service not healthy: [realtime-dev.supabase_realtime_limey supabase_pg_meta_limey supabase_studio_limey]
```

## System information

- OS: macOS 13.3.1
- RAM allocated to Docker: 12 GB

**Comment by cohlar** [comment] 2023-05-16 07:50
Same for me on Windows 11 after I upgraded from version 1.55.1 to 1.60.2.

**Comment by jramiroz98** [comment] 2023-05-29 20:44
Just found out the same bug on mine

**Comment by jramiroz98** [comment] 2023-05-30 00:48
Guys! This worked for me
`pnpx supabase start --ignore-health-check`

**Comment by romain-sen** [comment] 2023-06-12 14:16
I have the issue : 
```
$ npx supabase start        
supabase_rest_my-app container logs:
12/Jun/2023:14:09:05 +0000: Attempting to connect to the database...
12/Jun/2023:14:09:05 +0000: Connection successful
12/Jun/2023:14:09:05 +0000: Listening on port 3000
12/Jun/2023:14:09:05 +0000: Config reloaded
12/Jun/2023:14:09:05 +0000: Listening for notifications on the pgrst channel
12/Jun/2023:14:09:05 +0000: Schema cache loaded
12/Jun/2023:14:09:05 +0000: Attempting to connect to the database...
12/Jun/2023:14:09:05 +0000: Connection successful
12/Jun/2023:14:09:05 +0000: Config reloaded
12/Jun/2023:14:09:05 +0000: Schema cache loaded
12/Jun/2023:14:09:07 +0000: Attempting to connect to the database...
12/Jun/2023:14:09:07 +0000: Connection successful
12/Jun/2023:14:09:07 +0000: Config reloaded
12/Jun/2023:14:09:07 +0000: Schema cache loaded
12/Jun/2023:14:09:07 +0000: Attempting to connect to the database...
12/Jun/2023:14:09:07 +0000: Connection successful
12/Jun/2023:14:09:07 +0000: Config reloaded
12/Jun/2023:14:09:07 +0000: Schema cache loaded
12/Jun/2023:14:09:07 +0000: Attempting to connect to the database...
12/Jun/2023:14:09:07 +0000: Connection successful
12/Jun/2023:14:09:07 +0000: Config reloaded
12/Jun/2023:14:09:07 +0000: Schema cache loaded
supabase_deno_relay_my-app container logs:
Download https://deno.land/std@0.182.0/http/server.ts
Download https://deno.land/x/jose@v4.13.1/index.ts
Download https://deno.land/x/jose@v4.13.1/jwe/compact/decrypt.ts
[...]
Download https://deno.land/x/jose@v4.13.1/util/base64url.ts
Download https://deno.land/std@0.182.0/async/mod.ts
Download https://deno.land/x/jose@v4.13.1/lib/buffer_utils.ts
[...]
Download https://deno.land/x/jose@v4.13.1/runtime/generate.ts
Download https://deno.land/std@0.182.0/async/abortable.ts
[...]
Download https://deno.land/std@0.182.0/async/retry.ts
Download https://deno.land/x/jose@v4.13.1/lib/check_iv_length.ts
Download https://deno.land/x/jose@v4.13.1/runtime/check_cek_length.ts
Download https://deno.land/x/jose@v4.13.1/runtime/timing_safe_equal.ts
[...]
Download https://deno.land/x/jose@v4.13.1/lib/check_p2s.ts
Serving functions on http://localhost:54321/functions/v1/<function-name>
Error: service not healthy: [supabase_rest_my-app supabase_deno_relay_my-app]
Try rerunning the command with --debug to troubleshoot the error.
``` 
Debug bring no useful information and the flag --ignore-health-check allows me to finish `supabase start`, but then I can't query my db from my nextjs app without getting the error : `An invalid response was received from the upstream server`.

I am sure that I have enough ram (32gb). I tried to restart every container or delete and reinstall them but nothing work. Impossible to use the supabase cli... 
Anyone to help me ?

**Comment by romain-sen** [comment] 2023-06-13 08:32
I destroy all my docker container & images, and now it works.

**Comment by romain-sen** [comment] 2023-07-03 14:15
but even if it works with `--ignore-health-check` flag, the rest api doesn't work. I can run my db tests and it works. The studio works too, but the api does not. This does not help much.

**Comment by munkacsimark** [comment] 2023-07-23 12:27
I have similar issue, everything container is starting correctly except `supabase_studio_xxxxx`. The container keeps restarting then I'm getting the `service not healthy` error. `--ignore-health-check` flag works but this way I cannot start the studio. This log entry is repeating in the container:
```
info  - Loaded env from /app/studio/.env
Listening on port 3000
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
```
Any suggestion for this issue?

**Comment by NiklasPor** [comment] 2023-08-03 16:00
As a workaround downgrading to `1.69.0` worked for me. There's probably a more up-to-date version which also works. With the latest version I'm experiencing exactly the same issue as @munkacsimark on my mac.

**Comment by IbtisamBeik** [comment] 2023-08-04 15:17
I have same issue as @munkacsimark on my mac

**Comment by bllchmbrs** [comment] 2023-08-07 20:49
I have the same issue on my mac.

Unforunately, downgrading to `1.69` didn't work for me.

**Comment by NiklasPor** [comment] 2023-08-22 13:39
> As a workaround downgrading to `1.69.0` worked for me. There's probably a more up-to-date version which also works. With the latest version I'm experiencing exactly the same issue as @munkacsimark on my mac.

Actually I still have this error, even on the latest version `1.88.0`

**Comment by willdavidow** [comment] 2023-08-22 14:41
> > As a workaround downgrading to `1.69.0` worked for me. There's probably a more up-to-date version which also works. With the latest version I'm experiencing exactly the same issue as @munkacsimark on my mac.
> 
> Actually I still have this error, even on the latest version `1.88.0`

This should not be closed. Also still seeing this error using the latest `cli` version `1.88.0` (and the previous version when this issue was closed). Using `--ignore-health-check` still lets me around the issue so I can at least work locally.

**Comment by thomergil** [comment] 2023-08-23 00:59
I did a binary search between 1.69.0 and 1.88.0 and found that 1.72.0 works, and 1.73.0 no longer does. So 1.72.0 is the most recent version that does not exhibit this problem. Something broke between 1.72.0 and 1.73.0.

```
yarn remove supabase
yarn add supabase@1.72.0 --save-dev
yarn run supabase stop
yarn run supabase start
```

**Comment by sweatybridge** [comment] 2023-08-23 03:53
Thanks! This is really helpful. There studio version changed in 1.73.0 from 20230605 to 20230622 so there should be some commits between these dates that caused the crash loop on studio.

**Comment by sweatybridge** [comment] 2023-08-23 04:18
I think the major change between [these versions](https://github.com/supabase/supabase/compare/c876cea...d8395eb) is that studio is bumped from node16 to node18. It also seems like a platform specific issue.

@thomergil could you tell me more about your OS, arch, and docker version to help us reproduce?

**Comment by NiklasPor** [comment] 2023-08-23 06:47
FYI I'm experiencing this on:
- Intel MacOS (Ventura)
- Docker v4.21.1 (5 CPUs, 16 GB RAM)
- Package manager: pnpm v8.6.11

**Comment by thomergil** [comment] 2023-08-23 10:02
Only happens on my Intel Mac. Not on laptop... 🙂

**Comment by NiklasPor** [comment] 2023-08-23 13:35
> Thanks! This is really helpful. There studio version changed in 1.73.0 from 20230605 to 20230622 so there should be some commits between these dates that caused the crash loop on studio.

Weirdly enough, upgrading to the `1.91.0` beta also worked for me. Not sure if something was already fixed there or if the error is just flaky on intel macos.

**Comment by sweatybridge** [comment] 2023-08-24 06:10
I'm using an Intel based Mac without errors.. Could you also check the docker settings?

![Screenshot 2023-08-24 at 2 06 41 PM](https://github.com/supabase/cli/assets/1639722/dc7bb735-28e7-412d-8730-b26284465a66)

![Screenshot 2023-08-24 at 2 06 59 PM](https://github.com/supabase/cli/assets/1639722/96733433-fe2b-4fd5-ab7e-b02942cc1179)

**Comment by sweatybridge** [comment] 2023-08-24 06:53
UPDATE: I managed to reproduce this error after upgrading docker desktop to `4.21.1` (docker engine 24.0.1). I was previously on 4.12.0 (engine 20.10.17).

I will dig through their changelog to see if there's any fixes.

**Comment by sweatybridge** [comment] 2023-08-24 10:34
Found the upstream issue for this segfault https://github.com/docker/for-mac/issues/6824. If you are on Intel Mac with docker desktop versions >= 4.19.0, the workaround is to disable MacOS Virtualization Framework.

![Screenshot 2023-08-24 at 6 32 48 PM](https://github.com/supabase/cli/assets/1639722/bd83bef6-442f-4e14-aa87-862f32fe9e8f)

Closing this issue as unrelated to CLI.

**Closed by sweatybridge** 2023-08-24 10:34 UTC
Labels: bug

**Comment by thomergil** [comment] 2023-08-24 12:13
Thank you @sweatybridge!

**Comment by munkacsimark** [comment] 2023-08-24 13:54
Thanks a lot guys!

**Comment by bllchmbrs** [comment] 2023-08-29 14:56
Thank you for this!

**Comment by MortensenC** [comment] 2023-09-03 05:03
@sweatybridge, you are a genius! Many thanks

**Comment by myhendry** [comment] 2023-12-02 02:57
> Found the upstream issue for this segfault [docker/for-mac#6824](https://github.com/docker/for-mac/issues/6824). If you are on Intel Mac with docker desktop versions >= 4.19.0, the workaround is to disable MacOS Virtualization Framework.
> 
> ![Screenshot 2023-08-24 at 6 32 48 PM](https://private-user-images.githubusercontent.com/1639722/262946564-bd83bef6-442f-4e14-aa87-862f32fe9e8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0ODU4MjEsIm5iZiI6MTcwMTQ4NTUyMSwicGF0aCI6Ii8xNjM5NzIyLzI2Mjk0NjU2NC1iZDgzYmVmNi00NDJmLTRlMTQtYWE4Ny04NjJmMzJmZTllOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDI1MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE3MGFmNGNiZjRiY2U2MjBiNjY2MGUyNDcxMmQxNDFjOGFiZjgxZGM0MmExN2E3MzI2OWZiNjYwZTBhZTkxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TcKrI_68DisQbHuUqIZME4gtx-6hmf_4X98PHQVBwy8)
> 
> Closing this issue as unrelated to CLI.

Hi. I updated my docker desktop to version 4.25.2 and now it doesnt allow the user to uncheck the Use Virtualization framework checkbox. On my docker desktop, there is a footnote " Uses Virtualization framework for creating and managing Docker Desktop Linux VM in macOS 12.5 and above." As I'm now unable to disable Use Virtualization framework, im getting this message "service not healthy: [realtime-dev.supabase_realtime_server supabase_storage_server supabase_pg_meta_server supabase_studio_server]" when i run npx supabase start on my computer. Previously on an earlier version of docker desktop, i was able to uncheck Use Virtualization framework and everything was working nicely. Issue resurfaced when I upgraded my docker desktop 

Anyone has any solution to resolve this issue "service not healthy: [realtime-dev.supabase_realtime_server supabase_storage_server supabase_pg_meta_server supabase_studio_server]" now that I can't disable Uses Virtualization framework on docker desktop? Thanks

**Comment by philsherry** [comment] 2024-01-04 12:07
Do we know if there’s a way to do this in code? Rather than have to physically check a box on my Intel Macs, it would be nicer if I could just add something like this: 

```bash
if [[ ${CPU} == "x86_64" ]]; then
  MacOS_Virtualization_Framework=false
fi
```

**Comment by Mahogany95** [comment] 2024-02-06 10:25
I don't know why this is a closed issue. I have to uninstall Docker now in February 2024, Mac M1 chip. Docker goes in a loop. Maybe this is a Docker issue, but I never had to change my settings and cause Docker to crash. This only happened because of "service not healthy" issues.

That being said, **thank you for having supabase open source**! Thank you for all your hard work. I appreciate how tough it is.

Just for FYI though, this is what the suggestions in this thread put my Docker into:

![loop](https://github.com/supabase/cli/assets/63232814/63a37add-389e-4605-88da-72f2c28df788)

**Comment by sweatybridge** [comment] 2024-03-12 09:03
> Ultimately, I have to manually delete all my containers/images/volumes and re-run `supabase start` to set up a fresh local dev environment.

Have you tried `supabase stop --no-backup`? It should delete the volumes so it's easier to start from fresh.

**Comment by kiptoomm** [comment] 2024-03-12 09:37
> > Ultimately, I have to manually delete all my containers/images/volumes and re-run `supabase start` to set up a fresh local dev environment.
> 
> Have you tried `supabase stop --no-backup`? It should delete the volumes so it's easier to start from fresh.

I now have, and that indeed seems to be an easier way to cleanly reset the database. However, I'm still curious whether there's any longer-term solution or plans to fix it on the supabase CLI side for those of us where disabling the macOS virtualization as a workaround hasn't made any difference...

**Comment by ahmadawais** [comment] 2024-03-30 07:14
This fixed my problem, thank you @kiptoomm 

```sh
npx supabase stop --no-backup
npx supabase start
```

**Comment by Nurex-ui** [comment] 2024-05-19 09:23
I just had this, been working on idx, worked first run but then after closing and reopening the repo 2 or so days later, running **supabase start** got me this. What worked for me is removing images and reinitializing everything fresh.

**Comment by bel7aG** [comment] 2025-07-03 23:30
still 1 year later from the last comment on this issue
