### ISSUE TITLE
supabase db pull doesn't pull storage policies

### ISSUE THREAD

**Issue by zhadavi** [supabase/cli#1840] opened 2024-01-14 17:25 UTC
**Describe the bug**
Running `supabase db pull --schema storage` doesn't generate any SQL for the storage policies.

**To Reproduce**
1. Create some storage schema policies on dashboard
2. Run `supabase db pull --schema storage` locally
3. Inspect generated migration SQL and see that no SQL is generated for storage policies
4. Run studio via `supabase start` and see that no policies are under storage either

**Expected behavior**
Expected that storage policies would be generated in the migration

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser (if applicable) chrome
 - Version of CLI [e.g. v1.60.0] 1.131.4

**Comment by sweatybridge** [comment] 2024-01-16 10:13
closing as a duplicate https://github.com/supabase/cli/issues/1623

**Comment by sweatybridge** [comment] 2024-01-16 16:30
Hi @zhadavi, I can't reproduce this problem using cli version 1.131.4.

Could you share the output of `supabase services` for a quick version check?

**Comment by zhadavi** [comment] 2024-01-17 03:53
@sweatybridge sure:

```
❯ supabase services


        SERVICE IMAGE      │        LOCAL         │ LINKED
  ─────────────────────────┼──────────────────────┼─────────
    supabase/postgres      │ 15.1.0.147           │ -
    supabase/gotrue        │ v2.130.0             │ -
    postgrest/postgrest    │ v12.0.1              │ -
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.43.11             │ -
    supabase/edge-runtime  │ v1.29.1              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
 ```

**Comment by zhadavi** [comment] 2024-01-17 03:56
@sweatybridge sure

```
❯ supabase services


        SERVICE IMAGE      │        LOCAL         │   LINKED
  ─────────────────────────┼──────────────────────┼─────────────
    supabase/postgres      │ 15.1.0.153           │ 15.1.0.153
    supabase/gotrue        │ v2.132.3             │ v2.132.3
    postgrest/postgrest    │ v12.0.1              │ v12.0.1
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.43.11             │ v0.43.11
    supabase/edge-runtime  │ v1.29.1              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -
    ```

**Comment by sweatybridge** [comment] 2024-01-17 04:15
The versions look ok.

Could you double check that you have linked the right project by running `supabase projects list`?

If that's also ok, it might be specific to your hosted project. Please run `supabase db pull --schema storage --create-ticket` and reply the ticket id so we can look into it further.

**Comment by sweatybridge** [comment] 2024-01-17 05:04
Oh I see. This is indeed a misleading behaviour of CLI. If your local supabase/migrations directory is empty, db pull will ignore the `--schema` flag. I will make a PR to address this but meanwhile, you can work around it by pulling twice.

```
supabase db pull
supabase db pull --schema storage
```

**Closed** 2024-01-17 06:52 UTC

**Comment by la289** [comment] 2024-03-18 18:45
This seems to still be an issue. Running the command twice, the first time without the schema flag, doesnt help @sweatybridge

**Comment by jonathanlal** [comment] 2024-07-27 00:17
yeah also experiencing this issue still

**Comment by Madnex** [comment] 2024-11-15 16:12
Any update on this? Encountering the same problem

**Comment by SqlOwl** [comment] 2025-01-09 21:22
This is still an issue!!!

**Comment by Donald646** [comment] 2025-03-02 08:33
getting this issue right now
