### ISSUE TITLE
edge-runtime crashes in local development and cannot be restarted

### ISSUE THREAD

**Issue by evelant** [supabase/cli#1176] opened 2023-06-01 18:34 UTC
**Describe the bug**
edge-runtime container is crashing with exit 137 during local development. After it crashes it is not restarted automatically and cannot be restarted manually.

```
2023-06-01 14:11:04 Killed
2023-06-01 14:28:54 mkdir: cannot create directory '/home/deno/main': File exists
2023-06-01 14:30:11 mkdir: cannot create directory '/home/deno/main': File exists
```

The `mkdir: cannot create directory '/home/deno/main': File exists` error is preventing manual restart

**To Reproduce**
1. supabase start
2. call some edge functions
3. observe exit 137 crash
4. observe container does not restart and cannot be manually restarted

**Expected behavior**
Container should not crash. If it does crash it should restart automatically.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser (if applicable) N/A
 - Version of CLI 1.64.8
 - Version of supabase-js (if applicable) N/A
 - Version of Node.js (if applicable) N/A

**Additional context**
N/A

**Comment by laktek** [comment] 2023-06-04 20:42
Hey @evelant, Does this happen on any function or only when a particular function is called? Can you provide a minimal example of a function that crashes, so we can reproduce this issue on our end.

**Comment by evelant** [comment] 2023-06-05 12:24
@laktek I think this was actually an OOM because I had restricted docker's ram usage to 2gb. After giving docker more memory this hasn't reoccurred. Maybe it would be a good idea to add a note to the docs mentioning that the Supabase local development environment requires 2.5+ gb of memory configured in Docker? Or maybe it's possible for the CLI to read the docker config and issue a warning?

**Comment by laktek** [comment] 2023-06-05 19:46
Interesting! Let me do some stress testing and add some recommendations to to CLI Docker setup.

**Comment by sweatybridge** [comment] 2023-06-06 06:24
We used to recommend [7GB of RAM](https://supabase.com/docs/reference/cli/supabase-start) to start all docker services. But I think with recent improvements to our container images, we've brought down to around 3GB.

**Comment by evelant** [comment] 2023-06-06 14:13
Ouch, 7gb is a lot to allocate to docker on a common dev machine like a 16gb m1 macbook pro. It seems to work fine at 2.5gb now.

**Comment by laktek** [comment] 2023-06-09 00:35
Closing this issue since it's resolved.

**Closed by laktek** 2023-06-09 00:35 UTC
