### ISSUE TITLE
failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by edarioq** [supabase/cli#2713] opened 2024-09-28 09:16 UTC
**Describe the bug**
After updating to version `1.200.3` (from `1.191.3`) and when running `supabase start`  I get the following error:

```
failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Retrying after 4s: public.ecr.aws/supabase/postgres:15.6.1.115
failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Retrying after 8s: public.ecr.aws/supabase/postgres:15.6.1.115
Stopping containers...
failed to pull docker image: Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**To Reproduce**
1. Go to your project's directory
2. Run `supabase start`

**Expected behavior**
Should pull images and start containers

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 4023b7d67e0a446cac03d3b9457e0fe8
 - Version of OS: Sequoia
 - Version of CLI: 1.200.3
 - Version of Docker: Docker version 26.1.3, build b72abbb6f0
 - Versions of services:
supabase/postgres      │ 15.6.1.115       │ 15.6.1.115
    supabase/gotrue        │ v2.160.0         │ v2.160.0
    postgrest/postgrest    │ v12.2.3          │ v12.2.3
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.7          │ v1.11.7
    supabase/edge-runtime  │ v1.58.3          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -

**Additional context**
 In hindsight this issue could just be caused by macOS Sequoia and some recent firewall update, since disabling the FIrewall fixed the issue for me, if so feel free to close ticket.

**Comment by avallete** [comment] 2024-10-01 10:57
Seems like a firewall issue indeed, couldn't reproduce on my end:
```
a1cd23d4c0cb: Pull complete 
72c0feba4c79: Pull complete 
f36ff8486ea6: Pull complete 
Digest: sha256:8d3408fe35a09116b65c3c199e0298dd5d2a6d078122c7c9b2e00d76cf12b838
Status: Downloaded newer image for public.ecr.aws/supabase/postgres:15.6.1.115
```

Closing for now thank's for reporting.

**Closed by avallete** 2024-10-01 10:57 UTC
