### ISSUE TITLE
`supabase stop --backup` is not working

### ISSUE THREAD

**Issue by Gerschtli** [supabase/cli#715] opened 2022-12-17 15:11 UTC
# Bug report

## Describe the bug

Stopping the supabase docker container with `supabase stop` works but `supabase stop --backup` fails

## To Reproduce

I suspect some race conditions here. For me it is just running

```
supabase start
supabase stop --backup
```
The stop command prints (with `--debug`):
```
$ supabase stop --backup --debug
2022/12/17 15:55:38 Sent Header: Host [docker]
2022/12/17 15:55:38 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:38 Send Done
2022/12/17 15:55:38 Recv First Byte
2022/12/17 15:55:38 Sent Header: Host [docker]
2022/12/17 15:55:38 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:38 Sent Header: Content-Length [327]
2022/12/17 15:55:38 Sent Header: Content-Type [application/json]
2022/12/17 15:55:38 Send Done
2022/12/17 15:55:38 Recv First Byte
2022/12/17 15:55:38 Sent Header: Host [docker]
2022/12/17 15:55:38 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:38 Sent Header: Content-Length [2574]
2022/12/17 15:55:38 Sent Header: Content-Type [application/json]
2022/12/17 15:55:38 Send Done
2022/12/17 15:55:38 Recv First Byte
2022/12/17 15:55:38 Sent Header: Host [docker]
2022/12/17 15:55:38 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:38 Sent Header: Content-Length [0]
2022/12/17 15:55:38 Sent Header: Content-Type [text/plain]
2022/12/17 15:55:38 Send Done
2022/12/17 15:55:39 Recv First Byte
2022/12/17 15:55:39 Sent Header: Host [docker]
2022/12/17 15:55:39 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:39 Send Done
2022/12/17 15:55:39 Recv First Byte
2022/12/17 15:55:40 Sent Header: Host [docker]
2022/12/17 15:55:40 Sent Header: User-Agent [Go-http-client/1.1]
2022/12/17 15:55:40 Send Done
2022/12/17 15:55:40 Recv First Byte
Error: Error running pg_dump on local database: Error: No such container: 297f46b8662cc44525ae9446ec3b3a66b2d0fdcebf241c08bf5e7b4d8287cbad
```

## Expected behavior

No error message should occur, the containers should be stopped and a backup should be available.

## System information

- OS: Linux (NixOS)
- Version of supabase-cli: 1.26.9
- Version of docker: Docker version 20.10.21, build v20.10.21

## Additional context

I tried to fix the issue and this change solved the problem:
```diff
diff --git i/internal/utils/docker.go w/internal/utils/docker.go
index 38ebe94..6995ebd 100644
--- i/internal/utils/docker.go
+++ w/internal/utils/docker.go
@@ -307,7 +307,7 @@ func DockerRunOnce(ctx context.Context, image string, env []string, cmd []string
         Image: image,
         Env:   env,
         Cmd:   cmd,
-    }, container.HostConfig{AutoRemove: true}, "")
+    }, container.HostConfig{AutoRemove: false}, "")
     if err != nil {
         return "", err
     }
```

I seems to me that the start container, create backup, stop container and auto-remove container happens so fast that the `Docker.ContainerInspect` call fails because the container is not present anymore.

With this fix, the container to create the backup is still removed afterwards (`docker ps -a` does not show any containers), so it seems to be deleted afterwards either way.

I am not that familiar with this projects source code, but these are just my findings :)

**Comment by sweatybridge** [comment] 2022-12-19 05:25
Is your project pg14 or pg15? While I can't reproduce on pg14, I did find a issue with pg15 projects.

You can also add a status check between start and stop to make sure the db container is up.

```bash
supabase start
supabase status
supabase stop --backup
```

**Comment by Gerschtli** [comment] 2022-12-19 15:42
I can confirm with `supabase status` and `docker ps` that the containers are started correctly. I think the issue is with the docker container that is started only to dump the current database state for the backup.

Currently used  docker image for database by supabase: `public.ecr.aws/supabase/postgres:14.1.0.89`

**Comment by Gerschtli** [comment] 2022-12-19 15:57
Regarding your linked PR: This didn't solve the problem but required me to download a 5.85GB docker image for pg15.

```
$ supabase stop --backup
Error: Error running pg_dump on local database: Error: No such container: ee6148b6f6fce6b9e88f7ae2ed3f549091fe6e3cd43ef2a1d5f0758180e00430
Try rerunning the command with --debug to troubleshoot the error.
```

```
$ docker images | grep "postgres "
public.ecr.aws/supabase/postgres              15.1.0.11          0e960b74599f   5 days ago     5.85GB
public.ecr.aws/t3w2s2c9/postgres              14.1.0.89          667ab5e628e0   5 weeks ago    4.21GB
```

**Comment by sweatybridge** [comment] 2022-12-20 06:13
I managed to reproduce this issue by adding `time.Sleep(time.Second)` before `ContainerInspect`. I will work on a fix for this race condition.

The reason we need to download PG15 image is so that we converge on a single version of pg_dump. Old pg_dump has caused problems in the past where certain flags were not available. I'd also encourage you to upgrade your project to PG15 following [this guide](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#upgrade-your-project). If you are on a paid project, please contact support@supabase.io.

**Closed** 2022-12-20 07:30 UTC
Labels: bug
