### ISSUE TITLE
Recreating database throws error on `provider_id` column for google oauth users

### ISSUE THREAD

**Issue by KajSzy** [supabase/cli#1801] opened 2024-01-01 20:25 UTC
**Describe the bug**
I've dumped my production data to sql file for local development purpose.
Trying to reset local supabase instance I get an error that column type is invalid.

**To Reproduce**
1. Dump data from production (requires users signed up using google oauth)
`supabase db dump --data-only -f supabase/seed.sql`
2. Reset local supabase with new seed
`supabase db reset` locally

**Expected behavior**
As previous versions it was working fine, resetting local database should run smoothly for all signed up users.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of CLI: 1.127.4

**Additional context**

Both databases show `provider_id` column as `text`

```json
{
  "Type": "ErrorResponse",
  "Severity": "ERROR",
  "SeverityUnlocalized": "ERROR",
  "Code": "22P02",
  "Message": "invalid input syntax for type uuid: \"110207739924152032961\"",
  "Detail": "",
  "Hint": "",
  "Position": 1333,
  "InternalPosition": 0,
  "InternalQuery": "",
  "Where": "",
  "SchemaName": "",
  "TableName": "",
  "ColumnName": "",
  "DataTypeName": "",
  "ConstraintName": "",
  "File": "uuid.c",
  "Line": 133,
  "Routine": "string_to_uuid",
  "UnknownFields": null
}
```

**Comment by sweatybridge** [comment] 2024-01-02 09:26
This is probably caused by mismatched versions between local and prod. You can sync up local gotrue version to match remote by running `supabase link`.

Let me know if db reset works after relinking.

**Comment by KajSzy** [comment] 2024-01-02 11:07
Still throws same error, `supabase link` did not show any mismatches between local and remote

**Comment by sweatybridge** [comment] 2024-01-02 11:10
In that case, could you create a ticket and report the crash id for me to take a closer look?

```
supabase db reset --create-ticket
```

**Comment by KajSzy** [comment] 2024-01-02 11:43
> In that case, could you create a ticket and report the crash id for me to take a closer look?
> 
> ```
> supabase db reset --create-ticket
> ```

Ticket id: `90f0cd39e8d84df289525bad7e767e7d`

**Comment by sweatybridge** [comment] 2024-01-03 07:02
Could you try db reset again after `rm -rf supabase/.temp`? The crash ticket looks ok to me.

**Comment by KajSzy** [comment] 2024-01-03 11:27
Sadly, still same error. 
I'm quite sure it was working fine with older version but I am unable to test which one exactly.
Tried `beta` but still got same error

**Comment by sweatybridge** [comment] 2024-04-18 03:13
This seems to be a duplicate of https://github.com/supabase/supabase/issues/19620#issuecomment-1856418658

The resolution is to update supabase/seed.sql according to the steps in the linked comment.

**Closed by sweatybridge** 2024-04-18 03:13 UTC
