### ISSUE TITLE
Allow enabling/disabling all services in the config.toml configuration

### ISSUE THREAD

**Issue by daniel-j-h** [supabase/cli#1988] opened 2024-02-22 16:51 UTC
At the moment the `supabase/config.toml` allows us to disable some services e.g.

```toml
[realtime]
enabled = false
```

https://github.com/supabase/cli/blob/6eee42fe379c9199172a92604e66b4cfed2b0721/internal/utils/templates/init_config.toml

but it looks like some services are not configurable in the config file: for example by default it looks like the imgproxy and edge-runtime services are always getting started (i.e. their containers are started) on `supabase start`.

It seems like there is an exclude flag in the `supabase start` sub-command to disable them manually

    supabase start --exclude 'imgproxy,edge-runtime'

https://github.com/supabase/cli/blob/6eee42fe379c9199172a92604e66b4cfed2b0721/docs/supabase/start.md

Is this by design or an oversight?

Should there be sections in the config file `supabase init` creates and all other commands respect, such as

```toml
[imgproxy]
enabled = false

[edgeruntime]
enabled = false
```

Then we no longer have to enable/disable some services in the config and some on the command line via exclude flag.

**System information**
- OS: Linux
- Version of CLI: 1.145.4 (latest)

**Comment by sweatybridge** [comment] 2024-02-23 07:48
closing as a duplicate of https://github.com/supabase/cli/issues/1414

**Closed by sweatybridge** 2024-02-23 07:48 UTC
