### ISSUE TITLE
Ability to reset secrets for Edge functions with single command

### ISSUE THREAD

**Issue by CareTiger** [supabase/cli#1272] opened 2023-07-02 14:15 UTC
**Is your feature request related to a problem? Please describe.**
As a project evolves from POC to alpha to beta... etc, we start out with existing secrets from whatever existing  resource to show customers. we then slowly migrate to project and org specific secrets as user acceptance grows. 

**Describe the solution you'd like**
a simple command that will remove all hosted secrets
`supabase secrets reset --proj-ref <project-name>`

**Describe alternatives you've considered**
manually deleting secrets and then re-running
`supabase secrets set --env-file ./supabase/.env`

**Comment by sweatybridge** [comment] 2023-07-04 17:02
Seems like a duplicate of #1235. Feel free to reopen if that's not the case.

**Closed by sweatybridge** 2023-07-04 17:02 UTC
Labels: enhancement
