### ISSUE TITLE
Type generated for Views are incorrect set as optionally null

### ISSUE THREAD

**Issue by WesleyYue** [supabase/cli#603] opened 2022-11-13 17:36 UTC
# Bug report

## Describe the bug

Generated types for Views have field that are incorrectly marked "| null".

## To Reproduce

1. Have a table along the lines of:
```
CREATE TABLE IF NOT EXISTS public.table_name
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    field1 uuid NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT cell_pkey PRIMARY KEY (id)
)
```
2. Create a View like
```CREATE VIEW view_name AS SELECT id, created_at, field1 FROM public.name WHERE deleted_at IS NOT NULL;```
3. Generate types with `supabase type gen --local > types.ts`
4. Types come out something like
```
view_name: {
        Row: {
          id: number | null
          created_at: string | null
          field1: string | null
        }
...
```

## Expected behavior

Types should be:
```
view_name: {
        Row: {
          id: number
          created_at: string
          field1: string
        }
...
```

**Comment by soedirgo** [comment] 2022-11-17 05:38
Duplicate of https://github.com/supabase/cli/issues/577

**Closed by soedirgo** 2022-11-17 05:38 UTC
Labels: bug
