### ISSUE TITLE
CLI v1.69.1  breaks migrations and seed that depend on default schemas

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1257] opened 2023-06-27 18:08 UTC
**Describe the bug**

If your migrations depend on the default Supabase schema (triggers, column checks, custom functions, etc), the migration process fails because the schemas do no exist at the time of running migrations.

**To Reproduce**
1. Use CLI >=1.69.1
2. Have a migration that requires a column or table from supabase (for example the `auth` schema)
3. Run `supabase db reset`
4. Get similar error to:
```sh
Error: ERROR: column "phone" of relation "users" does not exist (SQLSTATE 42703)
```

**Expected behavior**
Supabase schema is available at migrations run time.

**Desktop (please complete the following information):**
 - OS: All
 - Version of CLI [e.g. v1.69.1.]

**Additional context**

**Comment by sweatybridge** [comment] 2023-06-27 19:59
Closing as duplicate of https://github.com/supabase/cli/issues/1255

**Closed** 2023-06-27 19:59 UTC
