### ISSUE TITLE
Cannot start supabase after stopping

### ISSUE THREAD

**Issue by leesus** [supabase/cli#135] opened 2022-01-06 15:44 UTC
# Bug report

## Describe the bug

After stopping local supabase with `Ctrl+C`, subsequent `supabase start` calls fail with the error: `Error starting database: ERROR:  database "main" does not exist`.

There is a SQL dump inside `supabase/.branches/main` directory.

I then have to nuke my supabase directory, then re-init.

## To Reproduce

1. `supabase init`
2. `supabase start`
3. `Ctrl+C` once instance is up
4. `supabase start`

## Expected behavior

`supabase start` restarts the instance once stopped.

## System information

- OS: macOS
- Version of supabase-js: 0.15.14
- Version of Node.js: 14.18.1

## Additional context

Fairly new to the Go CLI, I was using the old Docker setup without incident, so possibly I'm missing something simple.

**Comment by soedirgo** [comment] 2022-01-19 19:11
Sorry for the late reply! Can you see if the latest version (v0.16.1) fixes this? Issues related to branching should be curbed a bit. The new repro steps would be:
1. `supabase init`
2. `supabase start`
3. `supabase stop`
4. `supabase start`

**Comment by sweatybridge** [comment] 2022-08-17 10:44
Closing this issue since the containers are started in background in cli v1.

**Closed by sweatybridge** 2022-08-17 10:44 UTC
Labels: bug

**Comment by nextgenmetrics** [comment] 2023-01-15 14:54
This issue still regresses with cli v1.33.0.

Steps to reproduce:

1. supabase init
2. supabase start
3. Used the studio to create a schema and a table
4. supabase stop
5. supabase start --debug

Error ("Error restoring main: branch was not dumped") 

file attached

its obviously related to the .branch directory - when I delete the .branch it starts up fine, but I lose all the state and start from scratch.
 
[error.txt](https://github.com/supabase/cli/files/10420447/error.txt)

**Comment by sweatybridge** [comment] 2023-01-15 15:11
@leesus this is probably just a misleading log statement. Can you check `supabase status` after start to see if the db is actually running?

**Comment by nextgenmetrics** [comment] 2023-01-15 16:31
the containers are all terminated. so status returns an error.

…/supabase/projects/pragma/supabase  supabase status

Error: Error: No such container: supabase_db_pragma
Try rerunning the command with --debug to troubleshoot the error.

**Comment by nextgenmetrics** [comment] 2023-01-15 16:32
after the start, still errors

 …/supabase/projects/pragma/supabase  supabase start
Error restoring main: branch was not dumped.
Error: unlinkat supabase/.branches/main: operation not permitted
Try rerunning the command with --debug to troubleshoot the error.

**Comment by sweatybridge** [comment] 2023-01-15 23:16
> Error: unlinkat supabase/.branches/main: operation not permitted

This is a problem with local directory permission. Have you modified this before with chown/chmod? A quick fix is to delete .branches/main?

**Comment by espensgr** [comment] 2023-01-27 09:43
Getting the same error on every start even if i delete the .branches/main folder.
The `supabase status` returns no errors, i also dont get the unlinkat error, just the `Error restoring main: branch was not dumped.`
I guess it is not able to do a sql dump in that folder?
Using 1.34.5

**Comment by fRankete107** [comment] 2023-05-08 05:38
same error
