### ISSUE TITLE
Typescript generating results in docker error

### ISSUE THREAD

**Issue by wieli99** [supabase/cli#418] opened 2022-08-26 20:37 UTC
# Bug report

## Describe the bug

running `sudo supabase gen types typescript --db-url postgres://postgres:pass@db:port/postgres > src/components/database.types.ts` results in `Error: error running container`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
 
1. install CLI from package
2. `supabase init` in project folder
3. `supabase start`
4. `sudo supabase gen types typescript --db-url postgres://postgres:pass@db:port/postgres > src/components/database.types.ts`
5. results in `Error: error running container`

## Expected behavior
 
should generate typescript interfaces into src/components/database.types.ts

## System information

- OS: Fedora 36
- Version of supabase-js: new project on https://app.supabase.com/
- Version of Node.js: v16.14.0
- Version of Docker: 20.10.17, build 100c701

## Additional context

Done on a fresh installation of docker. `supabase start` runs without errors

**Comment by wieli99** [comment] 2022-08-26 22:11
To add: it works when I create a local copy of the database.

**Comment by magicseth** [comment] 2022-09-10 07:40
I am running in to this.

**Comment by magicseth** [comment] 2022-09-16 02:11
I'm really stuck here. Any thoughts on how to help provide a more useful error message so I can help find the root cause? I don't know how to create a local copy of the databse.  I've not used docker before, but I tried to create a supabase database commit, but ended up in a funky state and am terrified of overwriting my remote schema, which is the current correct schema.

**Comment by sweatybridge** [comment] 2022-10-14 04:25
Hello, sorry for getting back to you late on this one. We have added support for generating types on hosted projects using `--linked` or `--project-id` flags which run without docker.

For local database, docker is still required. You can also get debug logs by passing in `--debug` flag. Hope this helps.

duplicate of https://github.com/supabase/cli/issues/384

**Closed by sweatybridge** 2022-10-14 04:25 UTC
Labels: bug
