### ISSUE TITLE
`supabase link` hangs after adding database password

### ISSUE THREAD

**Issue by arpadgabor** [supabase/cli#899] opened 2023-03-01 12:02 UTC
# Bug report

## Describe the bug

Installed `supabase` using **homebrew** and I'm trying to link my local project. After inserting the database password and hitting enter, the process hangs and I can't do anything else. Ctrl + C does not work either. Any password I add and it just hangs, even if it's correct or not. I also tried restarting the project but got the same behavior.

## To Reproduce

1. Install with homebrew
2. `supabase link --project-ref=abc`
3. Insert db password, hit enter

## Expected behavior

Command should continue and show error/sucess.

## Screenshots

![Code_K7xkf6n8SR](https://user-images.githubusercontent.com/9270494/222131902-c8dd1569-04d4-408e-b339-43e4508192e2.png)

It just hangs like this forever.

## System information

- OS: Windows WSL2
- Browser (if applies) -
- Version of supabase-js: 2.8.0 (but I don't think it affects the issue)
- Version of supabase-cli: 1.40.4
- Version of Node.js: 16.19 or 18.14

## Additional context

n/a

**Comment by sweatybridge** [comment] 2023-03-01 12:06
This is a duplicate of https://github.com/supabase/cli/issues/819

**Comment by sweatybridge** [comment] 2023-03-01 12:21
All our envs are prefixed with `SUPABASE`. Can you give `SUPABASE_DB_PASSWORD` a try? I will reopen this for now.

**Comment by sweatybridge** [comment] 2023-03-01 12:22
It would also be helpful if you can share with us the logs after running with `--debug` flag

**Comment by arpadgabor** [comment] 2023-03-01 12:30
> All our envs are prefixed with SUPABASE

Ah okay. Tried now also with `--debug` but I'm getting nothing. However what I did find out is that if I run it outside my project it continues the process and then fails with

```
Error: cannot read config in /home/arpad/work: open supabase/config.toml: no such file or directory
Have you set up the project with supabase init?
```

Which is expected. But when running again in the project, it hangs with no logs.

```
✦ ❯ SUPABASE_DB_PASSWORD=abc supabase link --project-ref=xyz --debug

# nothing happening
```

**Comment by djordje** [comment] 2023-03-01 22:25
I had same issue in WSL2. Most likely you have WSLg (some GUI linux app) installed, which leads to some Gnome password (gnome keyring) manager which is actually leading to this command hanging.
What happens actually is UI popup to unlock vault is not appearing in Windows and it looks like command is hanging and you are not able to kill it.

In order to avoid this I actually use one distro without GUI apps which leads to supabase to use dotfiles to store credentials and everything works like on OSX or real Linux.

You can try `top` to find and kill gnome keyring by ID and it should start just fine next time you exec supabase link, but on next call you end up with same issue.

During my research I bumped into https://stackoverflow.com/questions/72528100/how-to-unlock-gnome-keyring-on-debian-headless-wsl-2-and-make-it-work-in-pytho and many more essentially leading to same problem.

**Comment by arpadgabor** [comment] 2023-03-03 17:14
Yeah I do have WSLg set up. Will check what you linked and report back if I find anything worthwhile.

**Comment by kapitanluffy** [comment] 2023-03-09 12:03
I am currently having the same problem when linking a project, I get this error.

```
Failed to save database password: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'
```

I use Linux Mint 21 Vanessa (based on ubuntu jammy).

**Comment by davingreen** [comment] 2023-03-16 03:19
Also having this issue on WSL 2 with Ubuntu distro on Windows 11... any solution? I can't link my supabase projects 😔

@djordje What distro do you have this working on?

**Comment by djordje** [comment] 2023-03-17 22:15
> Also having this issue on WSL 2 with Ubuntu distro on Windows 11... any solution? I can't link my supabase projects 😔
> 
> @djordje What distro do you have this working on?
> 
> UPDATE: Seems to happen regardless of distro. I've tried with Ubuntu, Red Hat flavor and Mint with same result.

I use latest Ubuntu, but I had to create new WSL2 distro and avoid any GUI apps to avoid WSLg. Works fine for me.

**Comment by arpadgabor** [comment] 2023-03-17 23:43
I managed to get it working by disabling wslg https://x410.dev/cookbook/wsl/disabling-wslg-or-using-it-together-with-x410/

**Comment by Bewinxed** [comment] 2023-07-05 06:04
On Ubuntu, ran into this issue, ran `top` and gnome-shell was running, and would keep restarting even if I killed the process.

**Solution**
`sudo service gdm stop`

-> Everything works.

**Comment by junedkhatri31** [comment] 2023-08-18 18:10
If you are on WSL and came to this issue by searching for `Failed to save database password: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'`
then,
1. Uninstall `gnome-keyring`
  ```
  sudo apt purge gnome-keyring
  sudo apt autoremove
  ```
2. Disable wslg by creating `.wslconfig` in `%USERPROFILE%` and add below content
  ```
  [wsl2]
  guiApplications=false
  ```
3. Shutdown wsl and again start
  ```
  wsl --shutdown
  ```

**Comment by Tortillaguy** [comment] 2023-09-08 14:03
> If you are on WSL and came to this issue by searching for `Failed to save database password: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'` then,
> 
> 1. Uninstall `gnome-keyring`
> 
> ```
> sudo apt purge gnome-keyring
> sudo apt autoremove
> ```
> 
> 2. Disable wslg by creating `.wslconfig` in `%USERPROFILE%` and add below content
> 
> ```
> [wsl2]
> guiApplications=false
> ```
> 
> 3. Shutdown wsl and again start
> 
> ```
> wsl --shutdown
> ```
> 
> 4. Install `gnome-keyring` again
> 
> ```
> sudo apt update
> sudo apt install gnome-keyring
> ```

I followed these instructions and still run into this error
`Failed to save database password: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'`

**Comment by jumaantony** [comment] 2023-09-15 13:18
@Tortillaguy this should work as I dont see the need to save the password locally

**Comment by DYAKOOO** [comment] 2023-09-19 05:05
It doesn't work no matter what I do , I killed gnome-keystring first and then uninstalled it but it was still not working. If you have it , its one problem , if you don't have it its another problem. I added my db password to env file as well , it still didn't work.

**Comment by DYAKOOO** [comment] 2023-09-19 05:06
Were you able to fix it @Tortillaguy

**Comment by sweatybridge** [comment] 2023-09-20 15:40
Apologies for the delay in addressing this issue. I will add some special handling for WSL in the next stable release so that the cli works more nicely out of the box.

**Closed** 2023-09-20 16:47 UTC
Labels: bug

**Comment by JamieGoodson** [comment] 2024-09-07 10:55
Having the same issue on WSL2:
```
Connecting to remote database...
Failed to save database password: Keyring is not supported on WSL
Finished supabase link.
```

Tried all of the suggested fixes in this thread. Environment variables, killing `gnome-keyring`, disabling `guiApplications`,  nothing works. Am completely blocked.

**Comment by KleiOz** [comment] 2024-11-10 19:46
Same issue here `Failed to save database password: Keyring is not supported on WSL` after following suggestions above. Thanks to @JamieGoodson I didn't waste that many time on that but I still feel unsecure 😁
