### ISSUE TITLE
Services getting exposed on network instead of only on localhost

### ISSUE THREAD

**Issue by daniel-j-h** [supabase/cli#1977] opened 2024-02-21 10:13 UTC
When running `supabase start` or `supabase db start` it looks like some services are getting exposed on the network, such as the postgres database. I believe this is because when we start containers they bind to all network interfaces instead of just localhost

https://github.com/supabase/cli/blob/7abddb09b604ea2789146b7f154c3b36a8822822/internal/db/start/start.go#L101-L150

This is both unexpected and a bit dangerous to suddenly have services exposed publicly in the network.

Ideally we'd expose services only on localhost - the equivalent of

    docker run -p 127.0.0.1:54322:54322

In case there are use cases where we really want to expose services publicly then what about we add a flag to the cli that changes the host from localhost to `0.0.0.0`?

**System information**
- OS: Linux
- Version of CLI: 1.145.4 (latest)

**Comment by sweatybridge** [comment] 2024-02-23 07:50
I will close this as a duplicate of https://github.com/supabase/cli/issues/1977

Feel free to upvote the issue to bump its priority.

**Closed by sweatybridge** 2024-02-23 07:50 UTC

**Comment by daniel-j-h** [comment] 2024-02-23 14:02
Ah I believe you wanted to link https://github.com/supabase/cli/issues/1397?
