### ISSUE TITLE
`function auth.jwt() does not exist` for local RLS

### ISSUE THREAD

**Issue by samwoolertonFosters** [supabase/cli#475] opened 2022-08-21 22:11 UTC
# Bug report

## Describe the bug

I defined RLS policies locally in the Supabase Studio UI, generated a migration file with `npm run db-diff <migration_name>`, and migrated in production with `supabase db push`.
After restarting the local DB with `supabase stop` and `supabase start`, it won't restart, instead throwing an error that `function auth.jwt() does not exist`. I can start the DB again by commenting out the migration code, but that would of course remove the RLS. I expect this should work locally and not just in production?
Using `\df` doesn't show any functions that could be typo-confused with `auth.jwt()`.
Not sure if related to [pgsodium changes](https://github.com/supabase/postgres/issues/274)?

## To Reproduce

- Add RLS policies locally that use `auth.jwt()` (to ge tthe user's email)
- Generate a migration
- Restart the local DB

## Expected behavior

DB to start and RLS to work (failing on the first of those)

## System information

- OS: Windows 11
- Version of supabase-js: in `package.json` as `^2.0.0-rc.1`
- Version of Node.js: 16.13.0
- `psql` version 12.7

Don't expect it's related, but I'm developing on Windows but running Postgres in WSL. This error is related to a function missing so shouldn't be relevant but mentioning in case it is!

**Comment by sweatybridge** [comment] 2022-09-26 07:38
Hi @samwoolertonFosters , this is likely due to an issue with outdated initial schema which we have [since fixed](https://github.com/supabase/cli/blame/7fa946098247b5afa08c9229cb584b25fd838ec5/internal/utils/templates/initial_schemas/14.sql#L268). Could you upgrade CLI and try again to see if it works?

Closing for now as I am not able to reproduce with `select auth.jwt();`. Feel free to reopen if you are still facing this issue.

**Closed by sweatybridge** 2022-09-26 07:38 UTC
Labels: bug

**Comment by FostersData** [comment] 2022-09-26 21:49
Working perfectly now thanks
